### ISSUE TITLE
Declare 204 with type null

### ISSUE THREAD

**Issue by guilhermegregio** [fastify/fastify-swagger#115]
When I declare the scheme as below

```
response: {
        204: {
          description: 'Succesful response',
        },
      },
```

I get the following stacktrace:

```
Error: undefined unsupported
    at build (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fast-json-stringify/index.js:94:13)
    at getValidatorForStatusCodeSchema (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fastify/lib/validation.js:13:10)
    at /Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fastify/lib/validation.js:19:21
    at Array.reduce (<anonymous>)
    at getResponseSchema (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fastify/lib/validation.js:18:22)
    at build (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fastify/lib/validation.js:58:31)
    at afterRouteAdded (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/fastify/fastify.js:607:9)
    at Object._encapsulateThreeParam (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/avvio/boot.js:387:7)
    at Boot.callWithCbOrNextTick (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/avvio/boot.js:311:5)
    at Boot._after (/Users/guilherme.gregio/Documents/easynvest/easynvest.preferencies/node_modules/avvio/boot.js:215:26)
``` 

When I try use type: 'null' 
```
response: {
        204: {
          type: 'null',
          description: 'Succesful response',
        },
      },
```

But the result is "Unknown Type: null" in model's section on swagger doc

**Comment by guilhermegregio** [comment]
I have fixed the issue removing the type when the value is 'null' in genResponse, this worked for me. Can you check it.

**Comment by StarpTech** [comment]
Correct me If I'm wrong but it looks to me that "null" isn't supported by OpenApi specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types You can use the special "nullable" type https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaNullable

**Comment by cemremengu** [comment]
@guilhermegregio is this still an issue for you? Did the discussion in #116 help?

**Comment by cemremengu** [comment]
Closing due to inactivity (and per #116). Feel free to reopen.

**Comment by avasuro** [comment]
Same issue - there is no way to set type: "null" for 204 response

**Comment by mcollina** [comment]
Feel free to open a new issue with a repro or open a PR to fix.
