### ISSUE TITLE
'Error: plugin must be a function' while using Jest coverage reporting

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify-swagger#162]
I've been stuck debugging this issue all day. I think I've finally figure out the source of the issue and it looks like it has something to do with Jest `coverage` generator, `fastify-swagger`, and `avvio`. 

On this PR: https://github.com/Ethan-Arrowood/matterhorn/pull/25
A user has added `fastify-swagger` to a basic `fastify` server. 

I'm using Jest for testing. `npm run test` works as expected. Everything is green.

Running `npm run test:ci` or `npm run coverage` (which both execute `jest --coverage` in some fashion) everything fails and blows up. 

I found this issue: https://github.com/swagger-api/swagger-node/issues/560#issuecomment-423742415 which mentions that the swagger doc generator doesn't exactly play nicely with Jest. I added `"collectCoverageFrom": [ "src" ]` to my jest.config.json in order to force the coverage reporter to only look at my actual source code. This resolved a really nasty (barely useful) error message and has now left me with the following:
```
👻 matterhorn (panbhatt-fastify_swagger_implementation %)▷ npm run test -- --coverage --coverageReporters=lcov

> matterhorn@0.1.1 test /Users/ethanarrowood/Documents/GitHub/matterhorn
> jest --config jest.config.json "--coverage" "--coverageReporters=lcov"

/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178
    throw new Error('plugin must be a function')
    ^

Error: plugin must be a function
    at Boot.Object.<anonymous>.Boot.use (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178:11)
    at Object.server.(anonymous function) [as register] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio
/boot.js:30:14)
    at Object.<anonymous>.module.exports [as dynamic] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/dynamic.js:35:13)
    at fastifySwagger (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/index.js:18:13)
    at Plugin.Object.<anonymous>.Plugin.exec (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:84:17)
    at Boot.loadPlugin (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:168:10)
    at Task.release (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:127:16)
    at worked (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:171:7)
    at done (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:129:5)
    at check (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:140:7)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
 PASS  tests/index.test.ts
/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178
    throw new Error('plugin must be a function')
    ^

Error: plugin must be a function
    at Boot.Object.<anonymous>.Boot.use (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178:11)
    at Object.server.(anonymous function) [as register] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio
/boot.js:30:14)
    at Object.<anonymous>.module.exports [as dynamic] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/dynamic.js:35:13)
    at fastifySwagger (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/index.js:18:13)
    at Plugin.Object.<anonymous>.Plugin.exec (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:84:17)
    at Boot.loadPlugin (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:168:10)
    at Task.release (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:127:16)
    at worked (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:171:7)
    at done (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:129:5)
    at check (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:140:7)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178
    throw new Error('plugin must be a function')
    ^

Error: plugin must be a function
    at Boot.Object.<anonymous>.Boot.use (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178:11)
    at Object.server.(anonymous function) [as register] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:30:14)
    at Object.<anonymous>.module.exports [as dynamic] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/dynamic.js:35:13)
    at fastifySwagger (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/index.js:18:13)
    at Plugin.Object.<anonymous>.Plugin.exec (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:84:17)
    at Boot.loadPlugin (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:168:10)
    at Task.release (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:127:16)
    at worked (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:171:7)
    at done (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:129:5)
    at check (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:140:7)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178
    throw new Error('plugin must be a function')
    ^

Error: plugin must be a function
    at Boot.Object.<anonymous>.Boot.use (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:178:11)
    at Object.server.(anonymous function) [as register] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/boot.js:30:14)
    at Object.<anonymous>.module.exports [as dynamic] (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/dynamic.js:35:13)
    at fastifySwagger (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastify-swagger/index.js:18:13)
    at Plugin.Object.<anonymous>.Plugin.exec (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:84:17)
    at Boot.loadPlugin (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:168:10)
    at Task.release (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:127:16)
    at worked (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/fastq/queue.js:169:10)
    at toLoad.finish (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:171:7)
    at done (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:129:5)
    at check (/Users/ethanarrowood/Documents/GitHub/matterhorn/node_modules/avvio/plugin.js:140:7)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
 FAIL  tests/plugins.test.ts
  ● Test suite failed to run

    Call retries were exceeded

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:177:21)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        7.605s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matterhorn@0.1.1 test: `jest --config jest.config.json "--coverage" "--coverageReporters=lcov"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matterhorn@0.1.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ethanarrowood/.npm/_logs/2019-03-12T01_47_07_774Z-debug.log
```
I'm now going to try and dig into these error messages, but I thought I'd post this issue in case someone could spot the mistake or propose a solution faster than I can.

FWIW, coverage works fine on the master branch (where there is no fastify-swagger installed). 

Some other areas I have debunked:
 - It is not caused by the directory structure or import structure of my `src/` contents
 - As far as I can tell everything has been updated (and works as expected on master)

**Comment by Ethan-Arrowood** [comment]
*facepalm*

in an attempt to solve a previous error I tried using `fastify.ready(async () => ...` and this was the cause of my error. My test causing this error:
```typescript
test('should return swager page on /documentation', () => {
  const fastify = createServer()

  fastify.ready(async () => {
    try {
      const response = await fastify.inject({ method: 'GET', url: '/documentation/static/index.html' })
      expect(response.statusCode).toEqual(200)
    } catch (error) {
      expect(error).toBeFalsy()
    }
  })
})
```

The easy fix to make everything work:
```typescript
test('should return swager page on /documentation', () => {
  const fastify = createServer()

  try {
    const response = await fastify.inject({ method: 'GET', url: '/documentation/static/index.html' })
    expect(response.statusCode).toEqual(200)
  } catch (error) {
    expect(error).toBeFalsy()
  }
})
```

Wow this was a wild adventure. I hope  all these issues help someone in the future 👍

**Comment by dound** [comment]
This issue can also occur if `fastify.ready()` is called multiple times.
