### ISSUE TITLE
Querystring not working with shared schema

### ISSUE THREAD

**Issue by eriott** [fastify/fastify-swagger#224]
## 🐛 Bug Report

Generating of swagger docs fails when I use shared schema (replace-way) in querystring.

## To Reproduce

1. Register fastify-swagger plugin.
1. Register any shared schema with id.
1. Create a route and use shared schema in querystring definition.
1. Run app and go to docs page.
1. An error happens:
 ```js
  TypeError: Cannot create property 'name' on string 'q'
    at Object.keys.forEach.prop (/home/regina/Projects/test-fastify-swagger/node_modules/fastify-swagger/dynamic.js:220:16)
    at Array.forEach (<anonymous>)
    at getQueryParams (/home/regina/Projects/test-fastify-swagger/node_modules/fastify-swagger/dynamic.js:217:22)
    at Object.swagger (/home/regina/Projects/test-fastify-swagger/node_modules/fastify-swagger/dynamic.js:144:11)
    at Object.handler (/home/regina/Projects/test-fastify-swagger/node_modules/fastify-swagger/routes.js:28:26)
    at preHandlerCallback (/home/regina/Projects/test-fastify-swagger/node_modules/fastify/lib/handleRequest.js:111:30)
    at preValidationCallback (/home/regina/Projects/test-fastify-swagger/node_modules/fastify/lib/handleRequest.js:100:5)
    at handler (/home/regina/Projects/test-fastify-swagger/node_modules/fastify/lib/handleRequest.js:69:5)
    at handleRequest (/home/regina/Projects/test-fastify-swagger/node_modules/fastify/lib/handleRequest.js:18:5)
    at onRunMiddlewares (/home/regina/Projects/test-fastify-swagger/node_modules/fastify/lib/middleware.js:22:5)

 ```

Use this code to reproduce error:

```js
const fastify = require('fastify')({
  bodyLimit: 1024 * 1024 * 2.5,
  ignoreTrailingSlash: true,
  logger: true
})

fastify.register(require('fastify-swagger'), {
  routePrefix: '/docs',
  exposeRoute: true,
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'testing the fastify swagger api',
      version: '0.1.0'
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
  }
})

fastify.addSchema({
  $id: 'query-schema',
  type: 'object',
  properties: {
    param1: {
      type: 'number'
    },
    param2: {
      type: 'string'
    }
  }
})

fastify.put('/some-route/:id', {
  schema: {
    description: 'post some data',
    tags: ['user', 'code'],
    summary: 'qwerty',
    querystring: 'query-schema#'
  }
}, (req, reply) => {})

fastify.ready(err => {
  if (err) {
    fastify.log.error('an error happened', err)
    throw err
  }
  fastify.log.info('fastify ready')
})

fastify.listen(4002, '0.0.0.0', async function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

## Expected behavior

I expect to see my shared schema definition in querystring on docs page.

## Your Environment

- *node version*: 11.15.0
- *fastify version*: 2.12.0
- *fastify-swagger version*: 2.5.0
- *os*:  Linux

**Comment by climba03003** [comment]
Resolved by https://github.com/fastify/fastify/pull/2108
If it happen again feel free to reopen the issue
