### ISSUE TITLE
fastify is not iterable

### ISSUE THREAD

**Issue by yidinghan** [fastify/fastify-swagger#26]
# Versions

| name | version |
| --- | --- |
| node | 8.9.0 |
| fastify | 0.40.0 |
| fastify-swagger | 0.3.1 |

# Error

```js
TypeError: fastify is not iterable
    at Function.swagger (/codes/node_modules/fastify-swagger/index.js:70:22)
    at fastify.ready (/codes/server.js:44:11)
    at Function._encapsulateThreeParam (/codes/node_modules/avvio/boot.js:332:7)
    at Boot.callWithCbOrNextTick (/codes/node_modules/avvio/boot.js:287:5)
    at release (/codes/node_modules/fastq/queue.js:127:16)
    at Object.resume (/codes/node_modules/fastq/queue.js:61:7)
    at Boot.Plugin.loadPlugin.call (/codes/node_modules/avvio/boot.js:141:20)
    at toLoad.finish (/codes/node_modules/avvio/plugin.js:108:7)
    at done (/codes/node_modules/avvio/plugin.js:66:5)
    at check (/codes/node_modules/avvio/plugin.js:77:7)
```
# Script

```js
const fastify = require('fastify')({
  logger: {
    level: 'info',
  },
});
const fastifySwagger = require('fastify-swagger');

const routes = require('./app/controller');

fastify.register(fastifySwagger, {
  swagger: {
    info: {
      title: 'insurance-agent-favor/backend',
      version: '0.1.0',
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
  },
  exposeRoute: true,
});
fastify.register(routes);

const start = async () => {
  try {
    await fastify.listen(3000);
    fastify.swagger();
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};
start();
```

# Else

It is ok with fastify@0.39.1

**Comment by delvedor** [comment]
Hi!
This happens with `v0.40.0` because we changed the internal api, we no  longer expose an iterator, but we expose an `onRoute` hook.
This plugin needs to be updated. I can do it as soon as I have time or you can send a pr if you prefer :)

https://github.com/fastify/fastify/blob/master/docs/Hooks.md#application-hooks
