### ISSUE TITLE
Plugin not working with JOI

### ISSUE THREAD

**Issue by vforv** [fastify/fastify-swagger#32]
Here is schema example for route: 

```
import * as Joi from 'joi';

export const PING_CREATE_VALIDATOR = {
    schema: {
        body: Joi.object({
            example: Joi.string().required(),
        }).required(),
    },
    schemaCompiler: (schema: any) => (data: any) => Joi.validate(data, schema),
};

```
Error:
```
TypeError: Cannot read property 'description' of null
    at Object.keys.forEach.p (node_modules/fastify-swagger/index.js:217:34)
    at Array.forEach (native)
    at getPathParams (node_modules/fastify-swagger/index.js:212:23)
    at Object.swagger (node_modules/fastify-swagger/index.js:121:11)
    at fastify.ready (src/app.ts:49:20)
    at Object._encapsulateThreeParam (node_modules/avvio/boot.js:345:7)
    at Boot.callWithCbOrNextTick (node_modules/avvio/boot.js:300:5)
    at Object.push (node_modules/fastq/queue.js:88:14)
    at Boot.ready (node_modules/avvio/boot.js:255:18)
    at Object.server.(anonymous function) [as ready] (node_modules/avvio/boot.js:46:21)
```

**Comment by mcollina** [comment]
This plugin assumes you are defining things with json-schema. We do not support Joi atm. If you want to contribute that with a PR, it would be welcomed!

We can also document this better, and maybe validate that the `schema` is in fact a json-schema (with ajv). A PR in this regard would be highly welcomed as well!

**Comment by mcollina** [comment]
Closing for no activity, feel free to reopen if it's still  a problem.

**Comment by gaboesquivel** [comment]
https://github.com/lightsofapollo/joi-to-json-schema

**Comment by allevo** [comment]
@gaboesquivel 
Nice!
Would you mind to send a PR in order to support Joi?

**Comment by gaboesquivel** [comment]
As soon as I get a chance. Lots of works right now 👍.

**Comment by Roms1383** [comment]
Guys I think this is fixed by https://github.com/fastify/fastify-swagger/pull/144. 😄 
Only thing you have to do is code a short `transform` method to map Joi schema back to standard JSON schema for Swagger documentation generation.

Have a working sample on [this repo](https://github.com/Roms1383/robust-database).

Only schema property you can't use with [Joi](https://github.com/hapijs/joi) is `response` as I ended up reporting to @mcollina [here](https://github.com/fastify/fastify-swagger/pull/144#issuecomment-456106235).
