### ISSUE TITLE
Crash when querystring/params/headers/cookies are references to global schemas

### ISSUE THREAD

**Issue by schantaraud** [fastify/fastify-swagger#394]
## 🐛 Bug Report

`fastify.swagger()` crashes when a route's querystring/params/headers/cookies is a reference to a global schema. e.g.:

```js
headers: {
  '$ref': 'http://example.com/headers#'
}
```

Error: `TypeError: Cannot read property 'schemas' of undefined`.
`lib/util/common.js:96:`
```js
  // $ref is in the format: #/definitions/<resolved definition>/<optional fragment>
  const localRef = jsonSchema.$ref.split('/')[2]
  return resolveLocalRef(externalSchemas[localRef], externalSchemas)
```
At this point, `$ref` is `#/components/schemas/def-1` and `externalSchemas` (`openapiObject.definitions`) is `undefined`.

I assume that this is not really supported at the moment but would like to help make it work if possible in an attempt to migrate a set of services from fastify-oas to this module. Any pointer would be appreciated. Will open a PR shortly.

May be related to #252

## To Reproduce

```js
const fastify = require('fastify')();

fastify.register(require('fastify-swagger'), {
  openapi: {},
  exposeRoute: true
});

fastify.addSchema({
  $id: 'http://example.com/body',
  type: 'object',
  properties: {
    hello: { type: 'string' }
  }
});

fastify.addSchema({
  $id: 'http://example.com/headers',
  type: 'object',
  properties: {
    mandatory: {
      type: 'boolean'
    }
  },
  required: ['mandatory']
});

fastify.post('/route', {
  schema: {
    body: {
      '$ref': 'http://example.com/body#'
    },
    headers: {
      '$ref': 'http://example.com/headers#'
    },
    // headers: {
    //   $id: 'http://example.com/headers',
    //   type: 'object',
    //   properties: {
    //     mandatory: {
    //       type: 'boolean'
    //     }
    //   },
    //   required: ['mandatory']
    // },
    response: {
      200: {
        '$ref': 'http://example.com/body#'
      }
    }
  }
}, (req, reply) => { reply.send({ hello: `Hello ${req.body.hello}` }) });

fastify.listen(3000, err => {
  if (err) throw err
  console.log(JSON.stringify(fastify.swagger()));
});
```

Result:
```
/node-sandbox/node_modules/fastify-swagger/lib/util/common.js:98
  return resolveLocalRef(externalSchemas[localRef], externalSchemas)
                                        ^

TypeError: Cannot read property 'schemas' of undefined
    at resolveLocalRef (/node-sandbox/node_modules/fastify-swagger/lib/util/common.js:98:41)
    at plainJsonObjectToOpenapi3 (/node-sandbox/node_modules/fastify-swagger/lib/spec/openapi/utils.js:95:41)
    at resolveCommonParams (/node-sandbox/node_modules/fastify-swagger/lib/spec/openapi/utils.js:185:15)
    at prepareOpenapiMethod (/node-sandbox/node_modules/fastify-swagger/lib/spec/openapi/utils.js:271:25)
    at Object.swagger (/node-sandbox/node_modules/fastify-swagger/lib/spec/openapi/index.js:45:29)
    at /node-sandbox/index.js:55:38
    at Server.wrap (/node-sandbox/node_modules/fastify/lib/server.js:80:9)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitListeningNT (net.js:1352:10)
```

## Expected behavior

```json
{
  "openapi": "3.0.3",
  "info": {
    "version": "4.5.0",
    "title": "fastify-swagger"
  },
  "components": {
    "schemas": {
      "def-0": {
        "type": "object",
        "properties": {
          "hello": {
            "type": "string"
          }
        }
      },
      "def-1": {
        "type": "object",
        "properties": {
          "mandatory": {
            "type": "boolean"
          }
        },
        "required": [
          "mandatory"
        ]
      }
    }
  },
  "paths": {
    "/route": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/def-0"
              }
            }
          }
        },
        "parameters": [
          {
            "in": "header",
            "name": "mandatory",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Default Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/def-0"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

## Your Environment

- *node version*: 14.16.1
- *fastify version*: 3.14.2
- *os*: Mac/Linux
- fastify-swagger@4.5.0

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by anonrig** [comment]
Hi all, is there any progress on this issue?

**Comment by anonrig** [comment]
This issue is resolved. We can close it

**Comment by schantaraud** [comment]
Thank you @anonrig
