### ISSUE TITLE
Querystring not working with "object" type

### ISSUE THREAD

**Issue by darcros** [fastify/fastify-swagger#489]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Plugin version

4.12.4

### Node.js version

16.11.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 21.04

### Description

I need to specify a required query parameter on a route, like this:
```js
querystring: {
  type: "object",
  name: { type: "string" },
  required: ["name"],
},
```
but this causes the plugin to throw an error.

I have verified that the error is thrown when `type` is set to `"object"` even if `required` is not defined:

* :x: throws
  ```js
  querystring: {
    type: "object",
    name: { type: "string" },
    required: ["name"],
  },
  ```
* :x: throws
  ```js
  querystring: {
    type: "object",
    name: { type: "string" },
  },
  ```
* :heavy_check_mark: does not throw
  ```js
  querystring: {
    name: { type: "string" },
  },
  ```

## Existing issues
By looking at old issues and pull requests it looks like what I'm trying to do should be supported (pull request #51), however I didn't create a regression report because I couldn't verify that this worked in previous version as this is the first time i try to do this.

### Steps to Reproduce

Here is a minimal reproducible example:
```js
const fastify = require("fastify")();
const fastifySwagger = require("fastify-swagger");

fastify.register(fastifySwagger, {
  routePrefix: "/documentation",
  exposeRoute: true,
  swagger: {
    info: {
      title: "Fastify API",
      description:
        "Building a blazing fast REST API with Node.js, MongoDB, Fastify and Swagger",
      version: "1.0.0",
    },
    host: "localhost",
    schemes: ["http"],
    consumes: ["application/json"],
    produces: ["application/json"],
  },
});
  
fastify.route({
  method: "GET",
  url: "/",
  schema: {
    querystring: {
      type: "object",
      name: { type: "string" },
      required: ["name"],
    },
    response: {
      200: {
        type: "object",
        properties: {
          hello: { type: "string", decription: "boh prova 1234" },
        },
      },
    },
  },
  handler: async (request, reply) => {
    return { hello: request.query.name };
  },
});

fastify.ready((err) => {
  if (err) throw err;
  fastify.swagger();
});

const start = async () => {
  try {
    await fastify.listen(3000);
    console.info("listening on port 3000");
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};
start();
```

stacktrace:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at resolveLocalRef (/home/darcros/Coding/my-api/node_modules/fastify-swagger/lib/util/common.js:112:36)
    at plainJsonObjectToSwagger2 (/home/darcros/Coding/my-api/node_modules/fastify-swagger/lib/spec/swagger/utils.js:99:15)
    at resolveCommonParams (/home/darcros/Coding/my-api/node_modules/fastify-swagger/lib/spec/swagger/utils.js:178:15)
    at prepareSwaggerMethod (/home/darcros/Coding/my-api/node_modules/fastify-swagger/lib/spec/swagger/utils.js:247:29)
    at Object.swagger (/home/darcros/Coding/my-api/node_modules/fastify-swagger/lib/spec/swagger/index.js:44:29)
    at /home/darcros/Coding/my-api/index.js:46:11
    at manageErr (/home/darcros/Coding/my-api/node_modules/fastify/fastify.js:493:11)
    at exit (/home/darcros/Coding/my-api/node_modules/fastify/lib/hooks.js:90:5)
    at manageTimeout (/home/darcros/Coding/my-api/node_modules/fastify/lib/hooks.js:107:11)
    at _encapsulateThreeParam (/home/darcros/Coding/my-api/node_modules/avvio/boot.js:551:7)
```

### Expected Behavior

The plugin does not throw an error and the server starts.

**Comment by climba03003** [comment]
Your schema is not a valid schema. `object` schema should comes with `properties`.

```js
querystring: {
  type: "object",
  properties: {
    name: { type: "string" },
  }.
  required: ["name"],
},
```
