### ISSUE TITLE
Openapi v3 Component Schema $ref in Fastify Schema Response

### ISSUE THREAD

**Issue by SaundersB** [fastify/fastify-swagger#583]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Plugin version

4.15.0

### Node.js version

14.4.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3.1

### Description

When registering Openapi v3 component schemas in the global config I'm seeing an error I can't seem to resolve when attempting to reference those component schemas in the fastify  endpoint schema.

**Plugin Registration:**
```

server.register(fastifySwagger, {
    mode: 'dynamic',
    staticCSP: true,
    routePrefix: '/${opts.prefix}/documentation',
    exposeRoute: true,
    openapi: {
      info: {
        title: 'API Swagger',
        description: 'Swagger API for the ${opts.prefix} service',
        version: '0.0.1',
      },
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
          },
        },
        schemas: {
          Participant: {
            type: 'object',
            required: ['id', 'email', 'password'],
            properties: {
              id: { type: 'string' },
              email: { type: 'string', format: 'email' },
              password: { type: 'string' },
              first_name: { type: 'string' },
              middle_name: { type: 'string' },
              last_name: { type: 'string' },
            },
          },
          User: {
            type: 'object',
            required: ['id', 'email', 'location_id', 'created_at'],
            properties: {
              id: { type: 'string' },
              email: { type: 'string', format: 'email' },
              password: { type: 'string' },
              first_name: { type: 'string' },
              middle_name: { type: 'string' },
              last_name: { type: 'string' },
            },
            example: {
              id: 1,
              email: 'sample@email.com',
              password: '1234',
              first_name: 'Jane',
              last_name: 'Doe',
            },
          },
        },
        responses: {
          User: {
            $ref: '#/components/schemas/User',
          },
        },
      },
    },
    uiConfig: {
      deepLinking: true,
    },
    uiHooks: {
      onRequest: function (request, reply, next) {
        next();
      },
      preHandler: function (request, reply, next) {
        next();
      },
    },
    transformStaticCSP: (header) => header,
  });
```

**Fastify Route**
```
fastify.get(
    '/locations',
    {
      description: 'retrieve program specific locations',
      schema: {
        headers: defaultHeadersJsonSchema,
        response: {
          200: {
            description: 'Successful retrieval of program specific locations',
            properties: {
              message: { type: 'string' },
              locations: {
                type: 'array',
                items: {
                  $ref: '#/components/schemas/User'
                },
              },
            },
          },
          400: {
            description: 'Invalid program detected',
            type: 'object',
          },
        },
      },
    },
    async function (req, reply) {
...
```

**Error:**
```
{
   "level":50,
   "time":1650459503376,
   "pid":15030,
   "hostname":"brandonsmacbook",
   "name":"FastifyError",
   "code":"FST_ERR_SCH_SERIALIZATION_BUILD",
   "message":"Failed building the serialization schema for GET: /authentication/incentive/locations, due to error Cannot find reference \"components\"",
   "statusCode":500,
   "stack":"FastifyError: Failed building the serialization schema for GET: /authentication/incentive/locations, due to error Cannot find reference \"components\"\n    at Boot.<anonymous> (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/authentication-api/webpack:/jnrcorp-apis/node_modules/fastify/lib/route.js:318:1)\n    at Object.onceWrapper (events.js:421:28)\n    at Boot.emit (events.js:327:22)\n    at Boot.EventEmitter.emit (domain.js:485:12)\n    at /Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/authentication-api/webpack:/jnrcorp-apis/node_modules/avvio/boot.js:153:1\n    at /Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/authentication-api/webpack:/jnrcorp-apis/node_modules/avvio/plugin.js:270:1\n    at done (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/authentication-api/webpack:/jnrcorp-apis/node_modules/avvio/plugin.js:202:1)\n    at check (/Users/bsaunders/src/awards/jnrcorp-apis/dist/apps/authentication-api/webpack:/jnrcorp-apis/node_modules/avvio/plugin.js:226:1)\n    at internal/process/task_queues.js:153:7\n    at AsyncResource.runInAsyncScope (async_hooks.js:189:9)",
   "type":"Error",
   "msg":"Failed building the serialization schema for GET: /authentication/incentive/locations, due to error Cannot find reference \"components\""
}
```

I've tried:

- $ref: '#User'
- $ref: '#/definitions/User'
- $ref: '#/components/schemas/user'
- $ref: 'User'

### Steps to Reproduce

- Declare component schemas in an openapi v3 global config.
- Attempt to reference that value in fastify schema endpoint

### Expected Behavior

Swagger should render an array of component schema definitions instead of declaring in-line properties which will be redundant. 

The response should look like this:
```
{
    message: { type: 'string' },
    locations: {
      type: 'array',
      items: {
        $ref: '#components/schemas/User',
      },
    },
  }
```

->
```
{
    message: { type: 'string' },
    locations: [{id: 1, name: 'something'}, {id: 2, name: 'something else'}],
  }
```

Otherwise I'd need to in-line every property:

```
{              
message: { type: 'string' },
              locations: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    id: { type: 'number' },
                    name: { type: 'string' },
                  },
                },
              },
            },
}
```

```
{
    message: { type: 'string' },
    locations: [{id: 1, name: 'something'}, {id: 2, name: 'something else'}],
  }
```

**Comment by climba03003** [comment]
You can never reference the `components` inside the doc since it is not supported.
Please use `fastify.addSchema` instead.

**Comment by SaundersB** [comment]
Oh good to know! Thank you!
