### ISSUE TITLE
$ref in allOf in query/headers causes Fastify to crash

### ISSUE THREAD

**Issue by HiiiiD** [fastify/fastify-swagger#604]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.1.0

### Node.js version

16.13.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 Build 19044.1706

### Description

`allOf` keyword put in `query` or `headers` schema causes Fastify to crash with this error
```
/app/node_modules/@fastify/swagger/lib/util/common.js:187
  return resolveLocalRef(externalSchemas[localRef], externalSchemas)
                                        ^

TypeError: Cannot read properties of undefined (reading 'schemas')
    at resolveLocalRef (/app/node_modules/@fastify/swagger/lib/util/common.js:187:41)
    at /app/node_modules/@fastify/swagger/lib/util/common.js:180:20
    at Array.reduce (<anonymous>)
    at resolveLocalRef (/app/node_modules/@fastify/swagger/lib/util/common.js:179:20)
    at plainJsonObjectToOpenapi3 (/app/node_modules/@fastify/swagger/lib/spec/openapi/utils.js:133:41)
    at resolveCommonParams (/app/node_modules/@fastify/swagger/lib/spec/openapi/utils.js:237:15)
    at prepareOpenapiMethod (/app/node_modules/@fastify/swagger/lib/spec/openapi/utils.js:339:29)
    at Object.swagger (/app/node_modules/@fastify/swagger/lib/spec/openapi/index.js:46:29)
    at prepare (/app/index.js:44:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to Reproduce

```javascript
const fastify = require('fastify')()

await fastify.register(require('@fastify/swagger'), {
    exposeRoute: true,
    routePrefix: '/docs',
    openapi: {
        info: { title: `Test OpenAPI`, version: '1.0.0' }
    }
})

fastify.addSchema({
    $id: 'test',
    type: 'object',
    properties: {
        field1: { type: 'integer' }
    }
})

fastify.put('/test-route', {
  schema: {
    query: {
        allOf: [{
            $ref: 'test'
        }, {
            type: 'object',
            properties: {
                field2: { type: 'string' }
            }
        }]
    },
    response: {
      200: {
          type: 'object',
          properties: {
              result: { type: 'string' }
          }
      }
    }
  }
}, (req, reply) => ({ result: 'OK' }))

await fastify.ready()
fastify.swagger()
```

### Expected Behavior

No error should occur.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by HiiiiD** [comment]
Of course. I'll create it asap

**Comment by HiiiiD** [comment]
@mcollina CI is currently failing. Should I create the pull-request even though is currently failing?
