### ISSUE TITLE
SwaggerTransform change from 8.14.0 -> 8.15.0 causes SwaggerTransformObject type exception

### ISSUE THREAD

**Issue by yuvenus** [fastify/fastify-swagger#809]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

8.14.0

### Stopped working in version

8.15.0

### Node.js version

18.20.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### 💥 Regression (or Bug?) Report

Hi there! We have a method that returns an `openapiObject` that is used to register swagger docs, like so:

```
function sampleMethodThatCreatesSwaggerObject() { 
    ...
    return openapiObject;
}

... later in the code

function initSwagger(
    server: FastifyInstance
) {
    server.register(fastifySwagger, {
        openapi: { ... },
        transformObject: sampleMethodThatCreatesSwaggerObject()
    }
}

```

And we've noticed that as a result our `@fastify/swagger` dependency updating from 8.14.0 to 8.15.0, we started receiving this error from the `initSwagger` method, due to `transformObject` no longer expecting the same type:

```
Overload 1 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }) => Partial<...>' is not assignable to type 'SwaggerTransformObject'.
      Types of parameters '__0' and 'documentObject' are incompatible.
        Type 'SwaggerDocumentObject' is not assignable to type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
          Property 'openapiObject' is missing in type '{ swaggerObject: Partial<Document<{}>>; }' but required in type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifySwagger' is not assignable to parameter of type 'FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
      Target signature provides too few arguments. Expected 3 or more, but got 2.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }) => Partial<...>' is not assignable to type 'SwaggerTransformObject'.

```

If my understanding is correct, it's due to this change in this PR that changes `transformObject`'s type from `{ swaggerObject, openapiObject` to `SwaggerTransformObject`: https://github.com/fastify/fastify-swagger/pull/807/files#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8 that updated the types. 

While we can update our method to return the correct type, is there cause for concern that this update isn't "backwards compatible," if that's the right term here?

Please let me know if there's more information that I can provide, and if this isn't a cause for concern, then I can close this. Thank you!!

### Steps to Reproduce

1. Have `@fastify/swagger@8.14.0` installed
2. Have any recent version of `fastify` installed
3. Run the code sample below and confirm that there are no type errors

```
import { OpenAPIV2, OpenAPIV3, OpenAPIV3_1 } from 'openapi-types';
import fastify, { FastifyInstance } from "fastify";
import fastifySwagger from '@fastify/swagger';

const fastifyServer: FastifyInstance = fastify();
const transformOpenapiObject = ({swaggerObject, openapiObject,}: {
    swaggerObject: Partial<OpenAPIV2.Document>;
    openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>;
}) => {
    return openapiObject;
}

fastifyServer.register(fastifySwagger, {
    openapi: {
        info: {
            title: 'test',
            description: 'test api',
            version: '1.0.0'
        }
    },
    transformObject: transformOpenapiObject
});
```
4. Update `@fastify/swagger` to `8.15.0`
5. Run the same code sample from step 3 and observe the following type error:
```
TSError: ⨯ Unable to compile TypeScript:
index.ts:13:15 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<OpenAPIV2.Document>; openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>; }) => Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<...>>' is not assignable to type 'SwaggerTransformObject'.
      Types of parameters '__0' and 'documentObject' are incompatible.
        Type 'SwaggerDocumentObject' is not assignable to type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
          Property 'openapiObject' is missing in type '{ swaggerObject: Partial<Document<{}>>; }' but required in type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifySwagger' is not assignable to parameter of type 'FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
      Target signature provides too few arguments. Expected 3 or more, but got 2.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<OpenAPIV2.Document>; openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>; }) => Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<...>>' is not assignable to type 'SwaggerTransformObject'.

13 fastifyServer.register(fastifySwagger, {
                 ~~~~~~~~

  index.ts:8:5
    8     openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>;
          ~~~~~~~~~~~~~
    'openapiObject' is declared here.

    at createTSError (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1621:12)     
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  diagnosticCodes: [ 2769 ]
}
```

### Expected Behavior

There shouldn't be a type error due to the version update.

**Comment by mcollina** [comment]
The first problem is that typescript does not follow semver, so _anything_ that is type based cannot really be trusted to be backward compatible at all. It's best effort to begin with.

Second, the case in question seemed a bugfix, and not really a change in API surface. I don't really understand what's the difference in your type vs the one we have to tell. 

A reproduction would help.

**Comment by yuvenus** [comment]
> The first problem is that typescript does not follow semver, so _anything_ that is type based cannot really be trusted to be backward compatible at all. It's best effort to begin with.
> 
> Second, the case in question seemed a bugfix, and not really a change in API surface. I don't really understand what's the difference in your type vs the one we have to tell.
> 
> A reproduction would help.

Makes sense! I've updated the ticket with more specificity and examples -- after a bit more digging, the "problem" happens when we attempt to assign the return of our helper method to the `transformObject` property when registering a FastifyInstance, like so:

```
function sampleMethodThatCreatesSwaggerObject(): openapiObject { 
    ...
    return openapiObject;
}

... later in the code

function initSwagger(
    server: FastifyInstance
) {
    server.register(fastifySwagger, {
        openapi: { ... },
        transformObject: sampleMethodThatCreatesSwaggerObject()
    }
}
```

The expected type for `transformObject` is no longer the same, thus causing the type error. Is this to be expected, and that we should update the return type of our helper method? Please let me know if there's more information I can provide as well. Thank you!

**Comment by mcollina** [comment]
Can you please provide a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by yuvenus** [comment]
Sure can do! I've updated the ticket as well with the same steps for clarity. Here are the steps:

1. Have `@fastify/swagger@8.14.0` installed
2. Have any recent version of `fastify` installed
3. Run the code sample below and confirm that there are no type errors

```
import { OpenAPIV2, OpenAPIV3, OpenAPIV3_1 } from 'openapi-types';
import fastify, { FastifyInstance } from "fastify";
import fastifySwagger from '@fastify/swagger';

const fastifyServer: FastifyInstance = fastify();
const transformOpenapiObject = ({swaggerObject, openapiObject,}: {
    swaggerObject: Partial<OpenAPIV2.Document>;
    openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>;
}) => {
    return openapiObject;
}

fastifyServer.register(fastifySwagger, {
    openapi: {
        info: {
            title: 'test',
            description: 'test api',
            version: '1.0.0'
        }
    },
    transformObject: transformOpenapiObject
});
```
4. Update `@fastify/swagger` to `8.15.0`
5. Run the same code sample from step 3 and observe the following type error:
```
TSError: ⨯ Unable to compile TypeScript:
index.ts:13:15 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<OpenAPIV2.Document>; openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>; }) => Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<...>>' is not assignable to type 'SwaggerTransformObject'.
      Types of parameters '__0' and 'documentObject' are incompatible.
        Type 'SwaggerDocumentObject' is not assignable to type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
          Property 'openapiObject' is missing in type '{ swaggerObject: Partial<Document<{}>>; }' but required in type '{ swaggerObject: Partial<Document<{}>>; openapiObject: Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<{}>>; }'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifySwagger' is not assignable to parameter of type 'FastifyPluginAsync<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger>'.
      Target signature provides too few arguments. Expected 3 or more, but got 2.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<SwaggerOptions, RawServerDefault, FastifyTypeProviderDefault, FastifyBaseLogger> | FastifyPluginAsync<...> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Type '({ swaggerObject, openapiObject, }: { swaggerObject: Partial<OpenAPIV2.Document>; openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>; }) => Partial<OpenAPIV3.Document<{}> | OpenAPIV3_1.Document<...>>' is not assignable to type 'SwaggerTransformObject'.

13 fastifyServer.register(fastifySwagger, {
                 ~~~~~~~~

  index.ts:8:5
    8     openapiObject: Partial<OpenAPIV3.Document | OpenAPIV3_1.Document>;
          ~~~~~~~~~~~~~
    'openapiObject' is declared here.

    at createTSError (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\vyu\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1621:12)     
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  diagnosticCodes: [ 2769 ]
}
```

Please let me know if there's more information I can provide. Thank you!

**Comment by mcollina** [comment]
Thanks for that, it was really helpful in understanding the situation. I think the types are indeed correct at this point. There are zero scenarios in which both `swaggerObject` and `openapiObject` can be both specified. Therefore, the new types are correct.

**Comment by yuvenus** [comment]
Great, glad that cleared it up! So for my understanding, this means this error is an intended side effect of changing the types, and we should go ahead and update our code to use the proper `SwaggerTransformObject` instead?

**Comment by mcollina** [comment]
yes exactly.
